### ISSUE TITLE
Project Todo list

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/Wii-Game-Studio#1]
Not really an 'issue' with the program, per-se, but more of a... well... todo list. :P
Basically the things on this list that are un-checked are in the most need of being added. More things obviously need to be done, but these are the most important atm.

- [ ] Add ability to 'find' resources by searching for them.

- [ ] Add settings that can be changed, saved, and loaded from a text/ini file to the settings form. Most importantly the path to Dolphin.

- [ ] Add functional resource editors for each type of resource (So far I've partially added the sprite/sound ones, but they don't really do anything yet.).

- [ ] Add ability to save projects to files/folders, generate code for them, and compile them. (The biggie!)

- [ ] Add Recent Projects list.

- [ ] Add documentation, including a wiki page, and link to it from within the application.

And probably more things that I'm forgetting... :/

**Comment by iyenal** [comment]
I can give you an host for the wiki page.

**Comment by Radfordhound** [comment]
Thanks for the offer! :) Though GitHub actually has a feature for creating Wiki pages for applications. ;)

**Comment by iyenal** [comment]
OK no problem
